/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorStore;
import Controlador.ControladorAddres;
import Controlador.ControladorCity;
import Controlador.ControladorCountry;
import Modelo.Addres;
import Modelo.Store;
import Modelo.City;

import Modelo.Country;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author crist
 */
public class StoreGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form StoreGUI2
     */
    public StoreGUI2() {
        initComponents();
        setLocationRelativeTo(null);
        agregarPaisescbx();
        agregarCiudadescbx(obteneridPais());
        agregarDireccionescbx(obteneridCity());
        cargarStore(obteneridAddres());
         
    }
private void limpiarListadoTabla(){
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jtListado.getModel();
        for(int i=modelo.getRowCount()-1; i>=0 ; i--){
            modelo.removeRow(i);
        }
    }
public void agregarPaisescbx(){
        ControladorCountry p= new ControladorCountry();
        ArrayList<Country>paises;
        paises= p.listadoCountry(0);
        /* if(paises.size()==0){
            cbxpais.addItem("");
        }else{*/
         
    for(int i=0;i<paises.size();i++){
         cbxpais.addItem(paises.get(i).getName()+" ID:"+paises.get(i).getCountryid());}
         //}
    }
public void agregarCiudadescbx(int country_id){
           cbxciudad.setModel(new javax.swing.DefaultComboBoxModel<>());
           ControladorCity p= new ControladorCity();
        ArrayList<City>ciudades;
        ciudades= p.listadoCity(country_id);
        
       /* if(ciudades.size()==0){
            cbxciudad.addItem("");
        }else{*/
    for(int i=0;i<ciudades.size();i++){
         cbxciudad.addItem(ciudades.get(i).getCity()+" ID:"+ciudades.get(i).getCity_id());}
     //}
       }
public void agregarDireccionescbx(int city_id){
           cbxaddres.setModel(new javax.swing.DefaultComboBoxModel<>());
           ControladorAddres p= new ControladorAddres();
        ArrayList<Addres>direcciones;
        direcciones= p.listadoAddres(city_id);
        /*if(direcciones.size()==0){
            cbxaddres.addItem("");
        }else{*/
    for(int i=0;i<direcciones.size();i++){
         cbxaddres.addItem(direcciones.get(i).getAddres()+" ID:"+direcciones.get(i).getAddresid());}
       // }
       }
 public int obteneridPais(){
        int id,pos;
         String cbx;
        cbx=cbxpais.getSelectedItem().toString();
        pos=cbx.lastIndexOf(":")+1; 
        id= Integer.parseInt(cbx.substring(pos));
        return id;
    }
 public int obteneridCity(){
        int id,pos;
         String cbx;
        cbx=cbxciudad.getSelectedItem().toString();
        pos=cbx.lastIndexOf(":")+1; 
        id= Integer.parseInt(cbx.substring(pos));
        return id;
    }
  public int obteneridAddres(){
        int id,pos;
         String cbx;
        cbx= cbxaddres.getSelectedItem().toString();
        
        pos=cbx.lastIndexOf(":")+1; 
        id= Integer.parseInt(cbx.substring(pos));
        return id;
    }
 public void cargarStore(int addres_id){
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jtListado.getModel();    
        ArrayList<Store> listado = new ArrayList();
        listado=ControladorStore.listadoStore(addres_id);
        limpiarListadoTabla();
        for(int i= 0; i < listado.size(); i++){
              modelo.addRow(new Object[]{
              listado.get(i).getStore_id(),
              listado.get(i).getManager_id(),
              listado.get(i).getAddres_id(),
              listado.get(i).getLast_update(),
              });
        }
    }
 //Este metodo permite calcular la id para un registro
 public int calcularId(){
     ArrayList<Store>all = new ArrayList();
     ControladorStore s = new ControladorStore();
     return s.listadoStore(0).size()+1;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        cbxpais = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        cbxciudad = new javax.swing.JComboBox<>();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListado = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setEnabled(false);
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setEnabled(false);
        jLabel8 = new javax.swing.JLabel();
        cbxaddres = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Staff ID");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ciudad");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Controles");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pais");

        btnNuevo.setText("Nuevo");
        btnNuevo.setActionCommand("b");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        cbxpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxpaisActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        cbxciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxciudadActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jtListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tienda ID", "Staff ID", "Direccion ID", "Last_Update"
            }
        ));
        jtListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListado);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 0, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tienda");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tienda ID");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Addres ID");

        cbxaddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxaddresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxpais, 0, 177, Short.MAX_VALUE)
                            .addComponent(cbxciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(cbxaddres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(btnNuevo)
                        .addGap(12, 12, 12)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbxciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxaddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        InterfazPrincipal ip =new InterfazPrincipal();
        setVisible(false);
        ip.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        jTextField1.setText(calcularId()+"");
        jTextField2.setText("");


        if(btnNuevo.getText().equals("Nuevo")){
            btnRegistrar.setEnabled(true);
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(true);
   
            cbxpais.setEnabled(false);
            cbxciudad.setEnabled(false);
            
            // jTextField5.setEnabled(true);
   
            btnRegistrar.setEnabled(true);
            btnBorrar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnNuevo.setText("Cancelar");
            jtListado.setEnabled(false);
            jTextField1.requestFocusInWindow();
        }
        else{
            btnRegistrar.setEnabled(false);
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            
            cbxpais.setEnabled(true);
            cbxciudad.setEnabled(true);
            // jTextField5.setEnabled(false);
            
            btnNuevo.setText("Nuevo");
            btnModificar.setEnabled(true);
            btnBorrar.setEnabled(true);
            jtListado.setEnabled(true);
            btnNuevo.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cbxpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpaisActionPerformed
        // TODO add your handling code here:
        agregarCiudadescbx(obteneridPais());
    }//GEN-LAST:event_cbxpaisActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(jTextField1.getText().trim().equals(""))
        JOptionPane.showMessageDialog(this,"Ingrese el Store ID");
        else{
            if (jTextField2.getText().trim().equals("")){
                JOptionPane.showMessageDialog(this,"Agregue  Staff ID");

            }
              
                    else{
                        if (cbxciudad.getSelectedItem().toString().equals("")){
                            JOptionPane.showMessageDialog(this,"Debe crear primero una ciudad");

                        }
                        else{
                        if (cbxpais.getSelectedItem().toString().equals("")){
                            JOptionPane.showMessageDialog(this,"Debe crear primero un pais");

                        }
                        else{
                        if (cbxaddres.getSelectedItem().toString().equals("")){
                            JOptionPane.showMessageDialog(this,"Debe crear primero una direccion");

                        }
                                else {
                                    Store a = new Store();
                                    a.setStore_id(calcularId());
                                    a.setManager_id(Integer.parseInt(jTextField2.getText()));
                                    a.setAddres_id(obteneridAddres());
                            
                                    Date date = new Date();
                                    a.setLast_update(new Timestamp(date.getTime()));

                                    int tamaño;
                                    tamaño = ControladorStore.listadoStore(a.getStore_id()).size();

                                    if(tamaño == 0){
                                        int resultado = 0;
                                        resultado = ControladorStore.grabarStore(a);
                                        if(resultado == 1){
                                            JOptionPane.showMessageDialog(this,
                                                "Direccion Grabado con éxito",
                                                "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(this,"Error al grabar",
                                                "Confirmación",JOptionPane.ERROR_MESSAGE);
                                        }

                                        cargarStore(obteneridAddres());

                                        btnNuevo.setText("Nuevo");
                                        jTextField1.setEnabled(false);
                                        jTextField2.setEnabled(false);
                                       cbxpais.setEnabled(true);
                                       cbxciudad.setEnabled(true);
                                       cbxciudad.setEnabled(true);

                                        //   jTextField5.setEnabled(false);
                           
                                        btnNuevo.setEnabled(true);
                                        btnRegistrar.setEnabled(false);
                                        btnBorrar.setEnabled(true);
                                        btnModificar.setEnabled(true);
                                        jtListado.setEnabled(true);
                                        btnNuevo.requestFocusInWindow();

                                    }
                                    else{
                                        JOptionPane.showMessageDialog(this,
                                            "ID ya registrado","Confirmación",
                                            JOptionPane.ERROR_MESSAGE);
                                        jTextField1.requestFocusInWindow();
                                    }

                                }
                            }    }}}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbxciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxciudadActionPerformed
        // TODO add your handling code here:
        agregarDireccionescbx(obteneridCity());
    }//GEN-LAST:event_cbxciudadActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if(jTextField1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione una Tienda","Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Desea Eliminar la direccion de id: " +
                jTextField1.getText().trim()+
                " ?", "Confirmación de Acción", JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
                int id = 0;
                id  = Integer.parseInt(jTextField1.getText().trim());

                if(ControladorAddres.borrarAddres(id) == 1){
                    JOptionPane.showMessageDialog(this,
                        "Registro Borrado con éxtio",
                        "Confirmación de acción",
                        JOptionPane.INFORMATION_MESSAGE);
                    cargarStore(obteneridAddres());
                }
                else{
                    JOptionPane.showMessageDialog(this,
                        "Error al borrar", "Confirmación de acción",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jtListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoMouseClicked
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jtListado.getModel();

        if(jtListado.getSelectedRow()==-1){
            if(jtListado.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"No hay registros");
            }
            else{
                JOptionPane.showMessageDialog(this,"Seleccione una fila");
            }
        }else {

            jTextField1.setText(modelo.getValueAt(jtListado.getSelectedRow(), 0).toString());
            jTextField2.setText(modelo.getValueAt(jtListado.getSelectedRow(), 1).toString());//////////////////////
            

           

        }
    }//GEN-LAST:event_jtListadoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(btnModificar.getText().equalsIgnoreCase("Modificar")){
            if(jtListado.getSelectedRow() == -1){
                if(jtListado.getRowCount() == 0){
                    JOptionPane.showMessageDialog(this,"No hay registros");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Seleccione una fila");
                }

            } else{

                jTextField2.setEnabled(true);
             
                //   jTextField5.setEnabled(true);
               
                btnBorrar.setEnabled(false);
                btnNuevo.setEnabled(false);
                btnRegistrar.setEnabled(false);
                btnModificar.setText("Actualizar");
                btnCancelar.setEnabled(true);
                jtListado.setEnabled(false);
            }
        } else {

            jTextField2.setEnabled(false);

            btnBorrar.setEnabled(true);
            btnNuevo.setEnabled(true);
            btnRegistrar.setEnabled(false);
            btnModificar.setText("Modificar");
            btnCancelar.setEnabled(false);
            jtListado.setEnabled(true);

           Store a = new Store();

            a.setStore_id(Integer.parseInt(jTextField1.getText()));
            a.setManager_id(Integer.parseInt(jTextField2.getText()));
            a.setAddres_id(obteneridAddres());
            
            Date date = new Date();
            a.setLast_update(new Timestamp(date.getTime()));

            if(ControladorStore.modificarStore(a) == 1){
                JOptionPane.showMessageDialog(this,"Actualización exitosa");
                this.cargarStore(obteneridAddres());
            } else {
                JOptionPane.showMessageDialog(this,"Actualización Fallida");
            }

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1FocusGained

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
       
        cbxpais.setEnabled(true);
        cbxciudad.setEnabled(true);
        //   jTextField5.setEnabled(false);
        
        btnBorrar.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnRegistrar.setEnabled(false);
        btnModificar.setText("Modificar");
        btnCancelar.setEnabled(false);
        jtListado.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.selectAll();
    }//GEN-LAST:event_jTextField2FocusGained

    private void cbxaddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxaddresActionPerformed
        // TODO add your handling code here:
        cargarStore(obteneridAddres());
    }//GEN-LAST:event_cbxaddresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxaddres;
    private javax.swing.JComboBox<String> cbxciudad;
    private javax.swing.JComboBox<String> cbxpais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable jtListado;
    // End of variables declaration//GEN-END:variables
}
